ni/nisystemlink-clients-python

docs/requirements.txt, tox.ini
Allows readthedocs.io to build the docs
Publish docs
Ran `tox -e docs`, and pointed readthedocs at my fork to check that *it* works, too
=> Move doc deps to a requirements.txt file, for readthedocs

.github/workflows/publish-to-pypi.yml
Automate publishing to PyPI
Less manual work
Used an equivalent workflow to publish a test python package to the PyPI Test server.
=> Add Publish-to-PyPI workflow

.github/workflows/python-package.yml
Passes a cloud API key added as a repo secret to tox.
Enables more automated testing surface for PR validation.
Ran tox locally with the same API key for py38.
=> Enable cloud integration testing for PRs

README.rst
Updates documentation links to point to our custom domain https://python-docs.systemlink.io and adds a badge pointing to the PyPI package.
Avoids the redirect from the old readthedocs.io page to the new one. Makes it easier to find which package and version is available.
Viewed the rendered page: https://github.com/ni/nisystemlink-clients-python/tree/users/pspangle/readme-links
=> Update README documentation and package links

conftest.py
Fixes the parameters passed by conftest.py for the --web-server-user and --web-server-password parameters.
Running the SystemLink Server integration tests with a non-default username or password currently fails.
Ran `tox -e py38 -- --web-server-url <server> --web-server-user <user> --web-server-password <password>`
=> Fix running SystemLink Server integration tests

.github/workflows/python-package.yml, .gitignore, mypy.ini, pyproject.toml, setup.py, tox.ini
`systemlink` is a [PEP-420 style namespace package](https://www.python.org/dev/peps/pep-0420/). This mechanism is used by Python-based SystemLink services, allowing the service code to live under the `systemlink` namespace, but exist elsewhere on the module search path, sandboxed outside of `site-packages`. After installing `nisystemlink-clients-python`, an `__init__.py` is dropped in the `site-packages` portion of the namespace, causing Python to ignore other packages within the namespace, elsewhere in the search path.
As [documented](https://packaging.python.org/guides/packaging-namespace-packages/):
> It is extremely important that every distribution that uses the namespace package omits the __init__.py or uses a pkgutil-style __init__.py. If any distribution does not, it will cause …
=> Ensure nisystemlink-clients-python treats systemlink as an implicit namespace package

setup.py, systemlink/clients/tag/_tag_data.py, systemlink/clients/tag/_tag_manager.py, tests/integration/tag/test_tagmanager.py, tests/tag/http/test_httpbufferedtagwriter.py, tests/tag/http/test_httptagselection.py, tests/tag/http/test_httptagsubscription.py, tests/tag/test_tagmanager.py
Manually open all prior versions of the .whl and notice that it contains a `tests` module. These files are also installed when `pip install`ing this package. We don't need to distribute tests, and they bloat the package unnecessarily.
This change updates the package exclusion rules to properly leave out everything under the `tests` directory.
In previous versions, there was an exclusion rule for `tests`, but this only instructs setup.py to exclude everything directly in the `tests` module, but does not exclude submodules. To exclude a module and its submodules, both `mymodule` and `mymodule.*` should be excluded - see [these docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages).
Examples were already not included because they do not contain an …
=> [setup.py] Prevent tests from being included in .whl

.gitignore, setup.py, systemlink/clients/tag/_buffered_tag_writer.py, tests/tag/http/test_httptagsubscription.py, tests/tag/test_bufferedtagwriter.py
This makes the buffered tag writer send any buffered writes on exit.
Resolves #14 
Ran all the tests that didn't need a local instance of SystemLink Server or the SystemLink Cloud setup.
=> send tag writes on buffered tag exit

systemlink/clients/core/__init__.py, systemlink/clients/core/_jupyter_http_configuration.py
Adds the `JupyterHttpConfiguration` class for use in Jupyter notebook environments.
This env variable based configuration is necessary for clients to work in notebooks.
We don't seem to have any unit tests around the config classes. There's really no functionality here other than reading env variables, so I didn't bother trying to create tests. We may be able to use this in integration tests for the DFS client later on.
=> Add JupyterHttpConfiguration class

conftest.py
Adds a session-level pytest fixture that sets the ["extra" config in Pydantic](https://pydantic-docs.helpmanual.io/usage/model_config/#options) models to "forbid".
Using this fixture will cause our tests to fail when new fields are added to DFS resources. This will force us to keep the client in sync with the service.
Ran tests locally and verified that it causes failures as expected.
=> Disallow extra Pydantic fields in tests

.github/workflows/python-package.yml
Splits the semantic-release step out to a separate job. The "build" step currently runs against a matrix of Python versions and we don't want to run the semantic-release tool multiple times.
Avoids an issue where we would attempt to build 4 releases per submission.
Commented out the conditional on the new job and verified it attempts to build a release (once):
https://github.com/ni/nisystemlink-clients-python/actions/runs/3482629028/jobs/5825222594
Current PR build shows that the job is skipped with the conditional uncommented.
=> chore: Split semantic-release out to a separate job

nisystemlink/clients/core/_uplink/_base_client.py, nisystemlink/clients/core/_uplink/_with_paging.py, nisystemlink/clients/dataframe/_data_frame_client.py, nisystemlink/clients/dataframe/models/__init__.py, nisystemlink/clients/dataframe/models/_paged_tables.py, nisystemlink/clients/dataframe/models/_query_tables_request.py, tests/integration/dataframe/test_dataframe.py
- Adds method to query tables with LINQ filter
- Queries are useful 😄 
- Added integration test that exercises all parameters
=> feat: Add query-tables method

nisystemlink/clients/dataframe/_data_frame_client.py, nisystemlink/clients/dataframe/models/__init__.py, nisystemlink/clients/dataframe/models/_modify_table_request.py, tests/integration/dataframe/test_dataframe.py
- Adds `update_table_metdata`method to patch table metdata.
The behavior of setting `null` to remove properties/fields relies on Pydantic's `exclude_unset` config: https://pydantic-docs.helpmanual.io/usage/exporting_models/
- Added automated test
Does anyone have input on the naming for the patch methods? I wasn't sure what to go with.
- `modify_table_metadata`
- `modify_table(s)`
- `patch_table(s)`
Keep in mind that we will need a name for the multi-patch method as well.
=> feat: Method to update table metadata

nisystemlink/clients/core/_api_error.py, nisystemlink/clients/core/_internal/_http_client.py, nisystemlink/clients/core/_uplink/_base_client.py, nisystemlink/clients/core/_uplink/_methods.py, nisystemlink/clients/dataframe/_data_frame_client.py, nisystemlink/clients/dataframe/models/__init__.py, nisystemlink/clients/dataframe/models/_delete_tables_partial_success.py, nisystemlink/clients/tag/_tag_manager.py, poetry.lock, pyproject.toml, tests/integration/dataframe/test_dataframe.py, tests/tag/test_tagmanager.py
- Adds `delete_tables` method to remove multiple tables in one call
- Refactors `core.ApiError` to be a Pydantic model so we can nest it in the delete partial success response
- Adds response body de-serialization that can handle Union types
- Adds wrappers around Uplink HTTP method decorators with naive typing to fix mypy errors and make client implementation simpler
- Added automated tests for delete methods
- Automated tag tests should hopefully cover ApiError refactor
=> feat: Table multi-delete + refactoring core libs

nisystemlink/clients/dataframe/_data_frame_client.py, nisystemlink/clients/dataframe/models/__init__.py, nisystemlink/clients/dataframe/models/_append_table_data_request.py, nisystemlink/clients/dataframe/models/_data_frame.py, nisystemlink/clients/dataframe/models/_paged_table_rows.py, poetry.lock, pyproject.toml, tests/integration/dataframe/test_dataframe.py
- `append_table_data` and `get_table_data` implemented
- Added automated test that writes data and then reads back a **mocked** response. The mock is a temporary solution until the service supports manual flushing of data.
- Manually tested reading data
Any opinions on the method names? I'm open to alternatives. (`write_table_data`, `read_table_data`)
Are there other test cases we should cover?
=> feat: Read and append table data

docs/api_reference/dataframe.rst, docs/conf.py, docs/index.rst
- Properly documents methods of `DataFrameClient`
The uplink decorators turns the functions into objects and Sphinx isn't auto documenting them meaningfully, even though the special methods like `__doc__` are preserved.
After some trial and error, I discovered that manually specifying the methods with `automethod::` gets Sphinx to treat the objects like functions and generate the correct docs.
- Reduces the clutter on the index page by reducing the TOC depth
It makes the docs better!
- See the built docs from this PR
=> Documentation fixes

nisystemlink/clients/dataframe/_data_frame_client.py
Fixes the following documentation bugs:
- We aren't documenting any "raises" such as ApiException
- The [DataFrameClient's \_\_init\_\_](https://python-docs.systemlink.io/en/latest/api_reference/dataframe.html#nisystemlink.clients.dataframe.DataFrameClient) references core.JupyterHttpConfiguration, but it didn't render as a link (compare to [TagManager.create_selection](https://python-docs.systemlink.io/en/latest/api_reference/tag.html#nisystemlink.clients.tag.TagManager.create_selection))
- Most of the DataFrameClient methods include a name for the return type that renders as a textual link instead of a code reference link.
Documentation fixes.
Checked docs produced as part of PR build.
=> fix: Fix various documentation issues

.github/workflows/python-package.yml
Pin the version of python-semantic-release to 7.34.3, which is the latest 7.x release. The 8.x releases [drastically changed](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html) how the utility is used.
Fix our release workflow so we can actually publish new versions (AB#2468953).
Verified the pip install command works. No other testing.
=> chore: Pin python-semantic-release to latest 7.x version

docs/api_reference.rst, docs/api_reference/testmonitor.rst, nisystemlink/clients/testmonitor/__init__.py, nisystemlink/clients/testmonitor/_test_monitor_client.py, nisystemlink/clients/testmonitor/models/__init__.py, nisystemlink/clients/testmonitor/models/_api_info.py, tests/integration/testmonitor/__init__.py, tests/integration/testmonitor/test_products.py
This PR adds support for the `/nitestmonitor/v2` API info routes. 
I am intentionally leaving out examples for now until we have more interesting examples to write.
This is the first pieces of a broader effort to support the `/nitestmonitor/v2` client.
Auto testing against a SLE instance has been added.
=> feat: test monitor API information routes client

nisystemlink/clients/core/_http_configuration_manager.py, nisystemlink/clients/dataframe/_data_frame_client.py, nisystemlink/clients/spec/_spec_client.py
Add `JupyterHttpConfiguration` as a fallback configuration for the `HttpConfigurationManager`. Allows the Clients to authenticate agnostic of the environment they're run from.
Enables SystemLink clients to adapt to supported run environments when using the default value for `configuration` arg like `client = DataFrameClient()`
Manual testing
- Run https://github.com/ni/nisystemlink-clients-python/blob/master/examples/dataframe/export_data.py on the computer with SystemLink Client connected with an SLE server
- `KeyError` occurs because `JupyterHttpConfiguration` is not available outside SLE
- Update the `DataFrameClient()` to use `core.HttpConfigurationManager.get_configuration()` as the default configuration
- Run the example, now, there should be no `KeyError` signifying that the client …
=> feat: Make DataFrame and Spec clients compatible with SystemLink Client http configuration

nisystemlink/clients/spec/_spec_client.py
Fix the bug where the `SpecClient()` result in error though the arg `configuration` is optional.
Enable users use `SpecClient()`  when run in SLE Jupyter executions or with SystemLink Client without passing an `HttpConfiguration` except for elevated privilege.
Run integration tests
Test using a simple spec query example on local machine with SystemLink Client connected to a SLE instance with valid specs.
```py
from nisystemlink.clients.spec import SpecClient
from nisystemlink.clients.spec.models import QuerySpecificationsRequest
client = SpecClient()
product_id = "e1ed79db-2d05-466b-a6d8-9872ec5cee54"
query_request = QuerySpecificationsRequest(product_ids=[product_id])
specs = client.query_specs(query_request)
print(specs.specs)
```
=> fix: Make SpecClient() work with default values for optional args

README.rst
remove reference to SystemLink Cloud
add reference to SystemLink Enterprise
correcting references to old and new SL products
correcting documentation
just documentation changes, no testing needed
=> fix: Remove SL Cloud from readme and add SLE

nisystemlink/clients/feeds/_feeds_client.py, tests/integration/feeds/test_feeds_client.py
- Fix the `DuplicateFeedsError` by updating the feedname generation in the tests.
- Fix the `MultipleRequestError` by adding retry decorator to `FeedsClient`.
Enable users to use FeedsClient without any issues.
Auto testing is included against NI's test tier.
[Swagger API Link](https://dev-api.lifecyclesolutions.ni.com/ninbexecution/swagger/index.html?urls.primaryName=Notebook+Execution+Artifact+Service)
=> test: Stabilize FeedsClient integration tests

nisystemlink/clients/testmonitor/models/_create_result_request.py, nisystemlink/clients/testmonitor/models/_result.py, nisystemlink/clients/testmonitor/models/_update_result_request.py, tests/integration/testmonitor/test_testmonitor.py
Test results can be created with `null` for `properties` value. eg. {"author": null}. The [PR](https://github.com/ni/nisystemlink-clients-python/pull/82) merge pipeline is failing while querying such results from the test env. To accommodate this, the results client has been modified to accept Optional value for properties.
Pipeline failure - [link](https://github.com/ni/nisystemlink-clients-python/actions/runs/13671574503/job/38222758606)
Ran automated tests against dev and test env
=> fix: Enable null value for results properties

nisystemlink/clients/testmonitor/utilities/_dataframe_utilities.py, tests/integration/testmonitor/test_testmonitor.py
In the Result Client test cases, a [fixture](https://github.com/ni/nisystemlink-clients-python/blob/820df0e39bea16dfe9f8bc5fad21a57efbb0194b/tests/integration/testmonitor/test_testmonitor.py#L49) is used to create results with a dummy part number. As per the design of the create-results API in SLE, a product is created with that dummy part number. This product should be deleted in the fixture itself once the linked results are deleted.
Implementation - All the products created during a test case are deleted by the fixture.
As the test suites are executed in the pipeline, the tests are continuously run which ended up polluting the test environment.
Verified the existing cases are passing
=> fix: Delete product created during result client test fixture

docs/getting_started.rst, nisystemlink/clients/testmonitor/utilities/__init__.py, nisystemlink/clients/testmonitor/utilities/_dataframe_utilities.py, nisystemlink/clients/testmonitor/utilities/constants.py, tests/testmonitor/__init__.py, tests/testmonitor/test_testmonitor_dataframe_utilities.py
- Adds functionality to return a normalized data frame, given a list of steps as input.
- Before the process of json normalization, inputs and outputs are restructured. From an array of names and values, they are converted into a dictionary with the name as the key, mapped to the value.
- Grouping of fields are done. This is much needed because, during normalization and the data frame conversion process, if there are new fields (especially fields which are nested) found in the successive steps, then there could be inconsistency in the ordering of the columns. (Also documented in the function's doc string)
This utility can be useful to get the steps data in the form of a Data frame which can be useful for further processing.
Unit tests are added
=> feat: Export steps as dataframe

CONTRIBUTING.md, pyproject.toml
- Updates maintainers 
- Points commit style to Conventional Commits instead of Angular
- Includes Python 3.13 in capabilities
- The owners have changed and our email addresses need updates
- Conventional Commits and Angular commits have the same style, but Conventional Commits has better documentation and is more specifically the style used by the commit parser
- We support python 3.13 and it should be documented as such
Chore change
=> chore: Update package metadata and contributing

nisystemlink/clients/notebook/_notebook_client.py
This adds retries to the notebook client for 429 rate limited responses, similar to other clients
The notebook integration tests will fail intermittently with 429 responses and this will make the tests more robust. This is also a generally nice to have improvement to the client that we have on other clients.
The integration tests are passing locally
=> fix: Add 429 retries to notebook client

.github/workflows/python-package.yml, tests/product/test_product_dataframe_utilities.py, tests/spec/test_spec_dataframe_utilitites.py, tests/testmonitor/test_testmonitor_dataframe_utilities.py
- Splits integration tests out into a separate job that runs with no parallelization
- Runs only unit tests in the main build job
- Updates some tests incorrectly marked enterprise
Integration tests modify shared state in the test environment and then running at the same time across python versions is causing intermittent test failures
PR
=> test: Stop running test in parallel

examples/testmonitor/results.py
Fixes two minor typos in the examples for `testmonitor`.
Cleanup.
Update to comments only. Does not require additional testing.
=> chore: two typos in the `testmonitor` examples

docs/getting_started.rst, examples/testmonitor/results.py
1. The steps example was not showing up in the getting started section of the documentation. 
2. The example for updating results was wrong. You can't use the return value from `create` to do an `update`.
Cleanup docs and fix example
Example code was tested locally.
=> fix: make testmonitor step examples show up in docs and fix `update_results` example

nisystemlink/clients/testmonitor/utilities/_dataframe_utilities.py, nisystemlink/clients/testmonitor/utilities/constants.py, tests/testmonitor/test_testmonitor_dataframe_utilities.py
1. Removed empty measurement columns when storing the steps DataFrame.
2. Included input columns while grouping.
3. Removed the status column from the DataFrame when all values are None.
To resolve minor bugs.
1. Added a test case to test the empty measurement scenario.
2. Input column grouping - Covered in the existing test cases.
3. None value for status column - Updated the existing test
=> fix: Handle none values and column grouping in results/steps dataframe utility

nisystemlink/clients/spec/models/_condition.py, tests/integration/spec/test_spec.py
Made `condition_type` optional when querying specs, allowing the use of projections in conditions without requiring a `condition_type`.
To enable the use of querying conditions without requiring a `condition_type`. 
Added a separate test.
=> fix: Make condition type optional while querying specs

nisystemlink/clients/testmonitor/models/_create_steps_request.py, tests/integration/testmonitor/test_testmonitor.py
Made the step_id Optional as mentioned in [https://github.com/ni/nisystemlink-clients-python/issues/121](url)
Bug fix
Added a separate test.
=> Fix: Create step should not require step_id

examples/general/disable_cert_verify.py, nisystemlink/clients/core/_http_configuration.py, nisystemlink/clients/core/_uplink/_base_client.py
Explicitly use the `requests` as the communication client package for `uplink` and expose the `requests.verify` to the user through `HttpConfiguration`
Allow SLE users with private CA to use the `systemlink-clients` package.
Automated tests.
=> feat: Make TLS/SSL certificate verification optional

nisystemlink/clients/spec/models/_condition.py, tests/integration/spec/test_spec.py
- It makes sure that string discrete values are correctly passing as string condition values numeric discrete values are correctly passing as numeric condition values.
- Data type of `discrete` value of `NumericConditionValue` is set to `List[Union[StringFloat, StrictInt]]`. Used StrictFloat and StrictInt because we only need integer and float values to be stored here and not string of numbers. If `int`/`float` are used, pydantic tries to convert the string of numbers into float/int.
- Data type of `discrete` value of `StringConditionValue` is set to `StrictStr`. Used `StrictStr` beause, we only want strings to be stored here and not any other datatypes. If `str` is used, pydantic converts any other datatypes to string and stores it.
- String discrete values which has string of numbers …
=> fix: Prevent string discrete values which are string of numbers from passing as numeric condition values.

nisystemlink/clients/dataframe/_data_frame_client.py
Adds retry decorator to `DataFrameClient` to handle common http status codes and connection errors.
Simplify developer experience in terms of handling common error situations
Existing automated Tests
=> feat: Add retry handling to DataFrameClient

docs/api_reference/spec.rst, docs/getting_started.rst, examples/spec/get_and_query_specs.py, nisystemlink/clients/core/_api_error_response.py, nisystemlink/clients/spec/_spec_client.py, tests/integration/spec/test_spec.py
This PR adds the `Get spec` API of the `Specification management service` to the spec client module.
It is helpful for users to retrieve a specification directly by its ID, rather than using the query API to fetch a single specification.
Automated integration tests are included.
API link: [Swagger link](https://dev-api.lifecyclesolutions.ni.com/niapis/?urls.primaryName=Specification+Management#/Specifications/get_nispec_v1_specs__id_)
=> feat: Spec client | Add Get Spec API 
